- name: Install required system packages
  apt:
    name:
      - python3-venv
      - python3-pip
      - tmux
    update_cache: yes

- name: Copy FastAPI files to EC2
  copy:
    src: "{{ item }}"
    dest: "/home/ubuntu/"
    owner: ubuntu
    group: ubuntu
    mode: '0644'
  loop:
    - main.py
    - requirements.txt

- name: Create a Python virtual environment
  command: python3 -m venv /home/ubuntu/fastapi-venv
  args:
    creates: /home/ubuntu/fastapi-venv

- name: Install Python packages in the virtual environment
  shell: /home/ubuntu/fastapi-venv/bin/pip install -r /home/ubuntu/requirements.txt
  args:
    executable: /bin/bash

- name: Run FastAPI with Uvicorn in a tmux session
  shell: tmux new-session -d '/home/ubuntu/fastapi-venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000'

